### ISSUE TITLE
Do not display Connection Lost if there's no data available

### ISSUE THREAD

**Issue by pew** [meteocool/core#107]
Not sure if I got this right. Don't display the "Connection Lost" banner when the API doesn't return any weather data for a given location. Just display the map.

<img width="568" alt="Screen_Shot_2021-03-31_at_3 54 08_PM" src="https://user-images.githubusercontent.com/52463/113244716-e09c2f00-92b5-11eb-950b-9585ce7d8803.png">

**Comment by v4lli** [comment]
Thanks for reporting, tried to fix it. Please try again + close if resolved.
