### ISSUE TITLE
Add "smart app banner" for Android

### ISSUE THREAD

**Issue by v4lli** [meteocool/core#51]
https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html

+ I'm sure there is something like this for android (as soon as 2.0 is released).

**Comment by pew** [comment]
There's no _native_ banner from google, only things like [smartbanner.js](https://github.com/ain/smartbanner.js), jquery or other plugins. I have no opinion about this.

**Comment by v4lli** [comment]
Would be cool to also have this for Android (in a lightweight way).

**Comment by v4lli** [comment]
Maybe when the Android app is more stable

**Comment by v4lli** [comment]
https://developers.google.com/web/fundamentals/app-install-banners/native#prefer_related
